package com.tamj0rd2.ktcheck

import com.tamj0rd2.ktcheck.GenerationException.OneOfEmpty
import com.tamj0rd2.ktcheck.core.Seed
import com.tamj0rd2.ktcheck.core.Tuple10
import com.tamj0rd2.ktcheck.core.Tuple2
import com.tamj0rd2.ktcheck.core.Tuple3
import com.tamj0rd2.ktcheck.core.Tuple4
import com.tamj0rd2.ktcheck.core.Tuple5
import com.tamj0rd2.ktcheck.core.Tuple6
import com.tamj0rd2.ktcheck.core.Tuple7
import com.tamj0rd2.ktcheck.core.Tuple8
import com.tamj0rd2.ktcheck.core.Tuple9
import com.tamj0rd2.ktcheck.core.shrinkers.IntShrinker
import com.tamj0rd2.ktcheck.core.tuple
import com.tamj0rd2.ktcheck.current.GenV2Builders
import java.util.*
import kotlin.collections.plus
import kotlin.plus
import kotlin.random.Random
import kotlin.reflect.KClass
import kotlin.sequences.plus
import kotlin.text.plus

interface Gen<T> {
    /**
     * Samples a value from the generator using the provided seed.
     *
     * @param seed The seed to use for sampling.
     * @return A sampled value of type T.
     */
    fun sample(seed: Long = Random.nextLong()): T

    /**
     * Produces an infinite sequence of samples from the generator using the provided seed.
     *
     * @param random The random instance used to create seeds for sampling. Defaults to [Random.Default].
     * @return A sequence of sampled values of type T.
     */
    fun samples(seed: Long = Random.nextLong()): Sequence<T> =
        Seed.sequence(Seed(seed)).map { sample(it.value) }

    /**
     * Prevents the default edge cases from being included
     */
    fun withoutDefaultEdgeCases(): Gen<T>

    /**
     * Produces a new generator by applying the provided function to the value generated by this generator.
     *
     * The shrinks from this generator are preserved in the resulting generator.
     *
     * Use this when you want to transform the values produced by a generator without changing its structure or shrinks.
     *
     * @param fn A function that takes a value of type T and returns a value of type R.
     * @return A new generator that produces values of type R.
     */
    fun <R> map(fn: (T) -> R): Gen<R>

    /**
     * Produces a new generator by applying the provided function to the value generated by this generator.
     * The resulting generator is then used to generate the final value.
     *
     * The shrinks from both generators are combined to provide a comprehensive set of shrinks for the final value.
     *
     * Use this when you want to create a generator that depends on the value produced by another generator.
     * If you instead want to combine two independent generators, consider using [plus] or [combineWith].
     *
     * @param fn A function that takes a value of type T and returns a generator of type R.
     * @return A new generator that produces values of type R.
     */
    fun <R> flatMap(fn: (T) -> Gen<R>): Gen<R>

    /**
     * Combines two independent generators using the provided combining function.
     *
     * The shrinks from both generators are combined to provide a comprehensive set of shrinks for the final value.
     *
     * Use this when you want to create a new generator that produces values based on two independent generators. i.e.
     * the value from one generator does not influence the value from the other generator.
     *
     * You can also combine independent generators using [Gens.zip] or [Gen.plus].
     *
     * For dependent generation (where the second generator depends on the first value), use [flatMap].
     *
     * @param nextGen The second generator to combine with this generator.
     * @param combine A function that takes values from both generators and combines them into a value of type R.
     * @return A new generator that produces values of type R.
     */
    fun <T2, R> combineWith(nextGen: Gen<T2>, combine: (T, T2) -> R): Gen<R>

    /**
     * Filters generated values using the given [predicate]. Although this generator supports shrinking, it is very
     * inefficient. Instead of using this generator, consider using generators that do not throw exceptions.
     */
    fun filter(predicate: (T) -> Boolean) = filter(100, predicate)

    /**
     * Filters generated values using the given [predicate]. Although this generator supports shrinking, it is very
     * inefficient. Instead of using this generator, consider using generators that do not throw exceptions.
     */
    fun filter(threshold: Int, predicate: (T) -> Boolean): Gen<T>

    /**
     * Ignores exceptions of type [klass] thrown during generation. Although this generator supports shrinking, it is very
     * inefficient. Instead of using this generator, consider using generators that do not throw exceptions.
     */
    fun ignoreExceptions(klass: KClass<out Exception>, threshold: Int = 100): Gen<T>

    /**
     * Generates lists of values from this generator with a size within the specified range.
     *
     * Edge cases include empty lists (if 0 in range), singleton lists (if 1 in range), and lists with duplicate
     * elements. The generator supports shrinking by reducing list size and shrinking individual elements.
     *
     * @param size The range of list sizes to generate. Defaults to 0..100.
     * @return A generator that produces lists of type T.
     */
    fun list(size: IntRange = 0..100): Gen<List<T>>

    fun list(size: Int): Gen<List<T>> = list(size..size)

    fun distinctList(size: IntRange): Gen<List<T>>

    fun distinctList(size: Int): Gen<List<T>> = distinctList(size..size)

    fun set(size: IntRange = 0..100): Gen<Set<T>> = distinctList(size = size).map { it.toSet() }

    fun set(size: Int): Gen<Set<T>> = set(size..size)
}

object Gens : GenBuilders by GenV2Builders

internal interface GenBuilders {
    fun <T> constant(value: T): Gen<T>

    fun bool(shrinkTarget: Boolean = false): Gen<Boolean> = int(
        range = 0..1,
        shrinkTarget = if (shrinkTarget) 1 else 0
    ).map { it == 1 }

    fun int(
        range: IntRange = Int.MIN_VALUE..Int.MAX_VALUE,
        shrinkTarget: Int = IntShrinker.defaultShrinkTarget(range),
    ): Gen<Int>

    fun long(): Gen<Long>

    fun uuid(): Gen<UUID> = long().combineWith(long(), ::UUID)

    // TODO: this should have a default
    fun char(chars: Iterable<Char>): Gen<Char> =
        oneOf(chars.distinct().sorted())

    /** Shrinks towards the first generator */
    fun <T> oneOf(vararg gens: Gen<T>): Gen<T> = oneOf(gens.toList())

    /** Shrinks toward the first generator */
    fun <T> oneOf(gens: Collection<Gen<T>>): Gen<T> {
        val gensList = gens.toList()
        return int(gensList.indices).flatMap { gensList[it] }
    }

    /** Shrinks toward the first value. Individual values will not be shrunk. */
    fun <T> oneOf(values: Iterable<T>): Gen<T> {
        val options = values.toList()
        if (options.isEmpty()) throw OneOfEmpty()
        return int(0..<options.size).map { options[it] }
    }

    /**
     * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
     *
     * @see [Gen.combineWith]
     */
    fun <T1, T2> zip(
        gen1: Gen<T1>,
        gen2: Gen<T2>,
    ): Gen<Tuple2<T1, T2>> =
        gen1.combineWith(gen2, ::tuple)

    /**
     * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
     *
     * @see [Gen.combineWith]
     */
    fun <T1, T2, T3> zip(
        gen1: Gen<T1>,
        gen2: Gen<T2>,
        gen3: Gen<T3>,
    ): Gen<Tuple3<T1, T2, T3>> =
        zip(gen1, gen2) + gen3

    /**
     * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
     *
     * @see [Gen.combineWith]
     */
    fun <T1, T2, T3, T4> zip(
        gen1: Gen<T1>,
        gen2: Gen<T2>,
        gen3: Gen<T3>,
        gen4: Gen<T4>,
    ): Gen<Tuple4<T1, T2, T3, T4>> =
        zip(gen1, gen2, gen3) + gen4

    /**
     * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
     *
     * @see [Gen.combineWith]
     */
    fun <T1, T2, T3, T4, T5> zip(
        gen1: Gen<T1>,
        gen2: Gen<T2>,
        gen3: Gen<T3>,
        gen4: Gen<T4>,
        gen5: Gen<T5>,
    ): Gen<Tuple5<T1, T2, T3, T4, T5>> =
        zip(gen1, gen2, gen3, gen4) + gen5

    /**
     * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
     *
     * @see [Gen.combineWith]
     */
    fun <T1, T2, T3, T4, T5, T6> zip(
        gen1: Gen<T1>,
        gen2: Gen<T2>,
        gen3: Gen<T3>,
        gen4: Gen<T4>,
        gen5: Gen<T5>,
        gen6: Gen<T6>,
    ): Gen<Tuple6<T1, T2, T3, T4, T5, T6>> =
        zip(gen1, gen2, gen3, gen4, gen5) + gen6

    /**
     * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
     *
     * @see [Gen.combineWith]
     */
    fun <T1, T2, T3, T4, T5, T6, T7> zip(
        gen1: Gen<T1>,
        gen2: Gen<T2>,
        gen3: Gen<T3>,
        gen4: Gen<T4>,
        gen5: Gen<T5>,
        gen6: Gen<T6>,
        gen7: Gen<T7>,
    ): Gen<Tuple7<T1, T2, T3, T4, T5, T6, T7>> =
        zip(gen1, gen2, gen3, gen4, gen5, gen6) + gen7

    /**
     * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
     *
     * @see [Gen.combineWith]
     */
    fun <T1, T2, T3, T4, T5, T6, T7, T8> zip(
        gen1: Gen<T1>,
        gen2: Gen<T2>,
        gen3: Gen<T3>,
        gen4: Gen<T4>,
        gen5: Gen<T5>,
        gen6: Gen<T6>,
        gen7: Gen<T7>,
        gen8: Gen<T8>,
    ): Gen<Tuple8<T1, T2, T3, T4, T5, T6, T7, T8>> =
        zip(gen1, gen2, gen3, gen4, gen5, gen6, gen7) + gen8

    /**
     * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
     *
     * @see [Gen.combineWith]
     */
    fun <T1, T2, T3, T4, T5, T6, T7, T8, T9> zip(
        gen1: Gen<T1>,
        gen2: Gen<T2>,
        gen3: Gen<T3>,
        gen4: Gen<T4>,
        gen5: Gen<T5>,
        gen6: Gen<T6>,
        gen7: Gen<T7>,
        gen8: Gen<T8>,
        gen9: Gen<T9>,
    ): Gen<Tuple9<T1, T2, T3, T4, T5, T6, T7, T8, T9>> =
        zip(gen1, gen2, gen3, gen4, gen5, gen6, gen7, gen8) + gen9

    /**
     * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
     *
     * @see [Gen.combineWith]
     */
    fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> zip(
        gen1: Gen<T1>,
        gen2: Gen<T2>,
        gen3: Gen<T3>,
        gen4: Gen<T4>,
        gen5: Gen<T5>,
        gen6: Gen<T6>,
        gen7: Gen<T7>,
        gen8: Gen<T8>,
        gen9: Gen<T9>,
        gen10: Gen<T10>,
    ): Gen<Tuple10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>> =
        zip(gen1, gen2, gen3, gen4, gen5, gen6, gen7, gen8, gen9) + gen10
}

fun Gen<Char>.string(size: IntRange): Gen<String> = list(size).map { it.joinToString("") }

fun Gen<Char>.string(size: Int) = string(size..size)

/**
 * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
 *
 * @see [Gen.combineWith]
 */
@JvmName("plus2")
infix operator fun <T1, T2> Gen<T1>.plus(
    nextGen: Gen<T2>,
): Gen<Tuple2<T1, T2>> =
    combineWith(nextGen) { first, second -> tuple(first, second) }

/**
 * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
 *
 * @see [Gen.combineWith]
 */
@JvmName("plus3")
infix operator fun <T1, T2, T3> Gen<Tuple2<T1, T2>>.plus(
    nextGen: Gen<T3>,
): Gen<Tuple3<T1, T2, T3>> =
    combineWith(nextGen) { tuple, nextValue -> tuple + nextValue }

/**
 * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
 *
 * @see [Gen.combineWith]
 */
@JvmName("plus4")
infix operator fun <T1, T2, T3, T4> Gen<Tuple3<T1, T2, T3>>.plus(
    nextGen: Gen<T4>,
): Gen<Tuple4<T1, T2, T3, T4>> =
    combineWith(nextGen) { tuple, nextValue -> tuple + nextValue }

/**
 * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
 *
 * @see [Gen.combineWith]
 */
@JvmName("plus5")
infix operator fun <T1, T2, T3, T4, T5> Gen<Tuple4<T1, T2, T3, T4>>.plus(
    nextGen: Gen<T5>,
): Gen<Tuple5<T1, T2, T3, T4, T5>> =
    combineWith(nextGen) { tuple, nextValue -> tuple + nextValue }

/**
 * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
 *
 * @see [Gen.combineWith]
 */
@JvmName("plus6")
infix operator fun <T1, T2, T3, T4, T5, T6> Gen<Tuple5<T1, T2, T3, T4, T5>>.plus(
    nextGen: Gen<T6>,
): Gen<Tuple6<T1, T2, T3, T4, T5, T6>> =
    combineWith(nextGen) { tuple, nextValue -> tuple + nextValue }

/**
 * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
 *
 * @see [Gen.combineWith]
 */
@JvmName("plus7")
infix operator fun <T1, T2, T3, T4, T5, T6, T7> Gen<Tuple6<T1, T2, T3, T4, T5, T6>>.plus(
    nextGen: Gen<T7>,
): Gen<Tuple7<T1, T2, T3, T4, T5, T6, T7>> =
    combineWith(nextGen) { tuple, nextValue -> tuple + nextValue }

/**
 * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
 *
 * @see [Gen.combineWith]
 */
@JvmName("plus8")
infix operator fun <T1, T2, T3, T4, T5, T6, T7, T8> Gen<Tuple7<T1, T2, T3, T4, T5, T6, T7>>.plus(
    nextGen: Gen<T8>,
): Gen<Tuple8<T1, T2, T3, T4, T5, T6, T7, T8>> =
    combineWith(nextGen) { tuple, nextValue -> tuple + nextValue }

/**
 * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
 *
 * @see [Gen.combineWith]
 */
@JvmName("plus9")
infix operator fun <T1, T2, T3, T4, T5, T6, T7, T8, T9> Gen<Tuple8<T1, T2, T3, T4, T5, T6, T7, T8>>.plus(
    nextGen: Gen<T9>,
): Gen<Tuple9<T1, T2, T3, T4, T5, T6, T7, T8, T9>> =
    combineWith(nextGen) { tuple, nextValue -> tuple + nextValue }

/**
 * Combines independent generators. The resulting generator produces a tuple of values, one from each input generator.
 *
 * @see [Gen.combineWith]
 */
@JvmName("plus10")
infix operator fun <T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> Gen<Tuple9<T1, T2, T3, T4, T5, T6, T7, T8, T9>>.plus(
    nextGen: Gen<T10>,
): Gen<Tuple10<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>> =
    combineWith(nextGen) { tuple, nextValue -> tuple + nextValue }

/**
 * Syntactic sugar for:
 *
 * ```kotlin
 * genA.flatMap { a -> makeGenB(a).map { b -> tuple(a, b) } }
 * ```
 *
 * and
 *
 * ```kotlin
 * genA.flatMap { a -> Gens.zip(Gens.constant(a), makeGenB(a)) }
 * ```
 */
@ExperimentalKtCheck
fun <T1, T2> Gen<T1>.retainAndFlatMap(f: (T1) -> Gen<T2>): Gen<Tuple2<T1, T2>> =
    flatMap { a -> f(a).map { b -> tuple(a, b) } }
