package com.tamj0rd2.ktcheck

import com.tamj0rd2.ktcheck.GenerationException.OneOfEmpty
import com.tamj0rd2.ktcheck.core.Seed
import com.tamj0rd2.ktcheck.core.shrinkers.IntShrinker
import com.tamj0rd2.ktcheck.v2.GenV2Builders
import java.util.*
import kotlin.random.Random
import kotlin.reflect.KClass

interface Gen<T> {
    /**
     * Samples a value from the generator using the provided seed.
     *
     * @param seed The seed to use for sampling.
     * @return A sampled value of type T.
     */
    fun sample(seed: Long = Random.nextLong()): T

    /**
     * Produces an infinite sequence of samples from the generator using the provided seed.
     *
     * @param random The random instance used to create seeds for sampling. Defaults to [Random.Default].
     * @return A sequence of sampled values of type T.
     */
    fun samples(seed: Long = Random.nextLong()): Sequence<T> =
        Seed.sequence(Seed(seed)).map { sample(it.value) }

    /**
     * Produces a new generator by applying the provided function to the value generated by this generator.
     *
     * The shrinks from this generator are preserved in the resulting generator.
     *
     * Use this when you want to transform the values produced by a generator without changing its structure or shrinks.
     *
     * @param fn A function that takes a value of type T and returns a value of type R.
     * @return A new generator that produces values of type R.
     */
    fun <R> map(fn: (T) -> R): Gen<R>

    /**
     * Produces a new generator by applying the provided function to the value generated by this generator.
     * The resulting generator is then used to generate the final value.
     *
     * The shrinks from both generators are combined to provide a comprehensive set of shrinks for the final value.
     *
     * Use this when you want to create a generator that depends on the value produced by another generator.
     * If you instead want to combine two independent generators, consider using [plus] or [combineWith].
     *
     * @param fn A function that takes a value of type T and returns a generator of type R.
     * @return A new generator that produces values of type R.
     */
    fun <R> flatMap(fn: (T) -> Gen<R>): Gen<R>

    /**
     * Combines two independent generators using the provided combining function.
     *
     * The shrinks from both generators are combined to provide a comprehensive set of shrinks for the final value.
     *
     * Use this when you want to create a new generator that produces values based on two independent generators. i.e
     * the value from one generator does not influence the value from the other generator.
     *
     * @param nextGen The second generator to combine with this generator.
     * @param combine A function that takes values from both generators and combines them into a value of type R.
     * @return A new generator that produces values of type R.
     */
    fun <T2, R> combineWith(nextGen: Gen<T2>, combine: (T, T2) -> R): Gen<R>

    /**
     * Combines two independent generators into a single generator that produces a tuple of both values.
     * Shrinking is performed independently on each component.
     *
     * Example:
     * ```
     * // Gen<Pair<Int, Boolean>>
     * val gen2 = Gen.int() + Gen.boolean()
     * ```
     *
     * To combine more than 2 generators, use [Gens.zip] instead.
     *
     * For dependent generation (where the second generator depends on the first value), use [flatMap].
     */
    infix operator fun <T2> plus(nextGen: Gen<T2>): Gen<Pair<T, T2>> = combineWith(nextGen, ::Pair)

    /**
     * Filters generated values using the given [predicate]. Although this generator supports shrinking, it is very
     * inefficient. Instead of using this generator, consider using generators that do not throw exceptions.
     */
    fun filter(predicate: (T) -> Boolean) = filter(100, predicate)

    /**
     * Filters generated values using the given [predicate]. Although this generator supports shrinking, it is very
     * inefficient. Instead of using this generator, consider using generators that do not throw exceptions.
     */
    fun filter(threshold: Int, predicate: (T) -> Boolean): Gen<T>

    /**
     * Ignores exceptions of type [klass] thrown during generation. Although this generator supports shrinking, it is very
     * inefficient. Instead of using this generator, consider using generators that do not throw exceptions.
     */
    fun ignoreExceptions(klass: KClass<out Exception>, threshold: Int = 100): Gen<T>

    // todo: at this point, some kind of builder could help with optional parameters
    fun list(size: IntRange = 0..100, distinct: Boolean = false): Gen<List<T>>

    fun list(size: Int, distinct: Boolean = false): Gen<List<T>> = list(size..size, distinct)

    fun set(size: IntRange = 0..100): Gen<Set<T>> = list(size = size, distinct = true).map { it.toSet() }

    fun set(size: Int): Gen<Set<T>> = set(size..size)
}

object Gens : GenBuilders by GenV2Builders {
    fun Gen<Char>.string(size: IntRange): Gen<String> = list(size).map { it.joinToString("") }
    fun Gen<Char>.string(size: Int) = string(size..size)
}

internal interface GenBuilders {
    fun <T> constant(value: T): Gen<T>

    fun bool(shrinkTarget: Boolean = false): Gen<Boolean>

    fun int(
        range: IntRange = Int.MIN_VALUE..Int.MAX_VALUE,
        shrinkTarget: Int = IntShrinker.defaultShrinkTarget(range),
    ): Gen<Int>

    fun long(): Gen<Long>

    fun uuid(): Gen<UUID> = (long() + long()).map { UUID(it.first, it.second) }

    fun char(chars: Iterable<Char>): Gen<Char> =
        oneOf(chars.distinct().sorted())

    /** Shrinks towards the first generator */
    fun <T> oneOf(vararg gens: Gen<T>): Gen<T> = oneOf(gens.toList())

    /** Shrinks toward the first generator */
    fun <T> oneOf(gens: Collection<Gen<T>>): Gen<T>

    /** Shrinks toward the first value. Individual values will not be shrunk. */
    fun <T> oneOf(values: Iterable<T>): Gen<T> {
        val options = values.toList()
        if (options.isEmpty()) throw OneOfEmpty()
        return int(0..<options.size).map { options[it] }
    }
}
